module.exports=(Sequelize,DataTypes)=>{
    return{
        id:{
            type:DataTypes.UUID,
            defaultValue:Sequelize.UUID,
            primaryKay:true
        },
        isBlocked:{
            type:DataTypes.TINYINT(1),
            defaultValue:0,
        },
        isDeleted:{
            type:DataTypes.TINYINT(1),
            defaultValue:0  
        },
        createdAt:{
            type:DataTypes.DATE,
            defaultValue:DataTypes.NOW(0)
        },
        updatedAt:{
            type:DataTypes.DATE,
            defaultValue:DataTypes.NOW(0)
        }
    }
}